language: node_js
sudo: false
node_js:
  - '6.6.0'

addons:
#  firefox: "38.0"
  apt:
    sources:
      # needed to install g++ that is used by npms's native modules
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
     - ./node_modules
     - ./.chrome/chromium

env:
  global:
    # GITHUB_TOKEN
    # This is needed for the e2e Travis matrix task to publish packages to github for continuous packages delivery.
    - secure: ""
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
   - CI_MODE=js
   - CI_MODE=e2e
   - CI_MODE=saucelabs_required
   - CI_MODE=browserstack_required
   - CI_MODE=saucelabs_optional
   - CI_MODE=browserstack_optional

matrix:
  fast_finish: true
  allow_failures:
    - env: "CI_MODE=saucelabs_optional"
    - env: "CI_MODE=browserstack_optional"

install:
  npm install -g npm@6

script:
  npm test
